spring:
  application:
    name: client

server:
  port: 8081

otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: client-service
      service: client-service
      env: dev

article:
  service:
    base-url: http://localhost:8082